version: "3.3"

services:
    apache:
      image: php:apache
      container_name: apache
      ports :
       - "8081:80"
      volumes:
       - ./:/var/www/html
      links:
       - database:db
    phpmyadmin:
       image: phpmyadmin/phpmyadmin
       container_name: phpmyadmin
       ports :
        - "8082:80"
       environment:
        - MYSQL_USERNAME=root
        - MYSQL_PASSWORD=password
       links:
        - database:db
    database:
       image: mariadb:latest
       container_name: database
       ports:
        - "3306:3306"  
       environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=soutenancePhp