apache:
  image: php:apache
  ports :
   - "8081:80"
  volumes:
   - /SoutenancePHPDOCKER/:/var/www/html
  links:
   - database
phpmyadmin:
   image: corbinu/docker-phpmyadmin
   ports :
    - "8082:80"
   environment:
    - MYSQL_USERNAME=root
    - MYSQL_PASSWORD=password
   links:
    - database:mysql
database:
  image: mysql:latest
  ports:
   - "3306:3306"  
  environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=soutenancePhp
     - MYSQL_USER=mysite
     - MYSQL_PASSWORD=password